In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import joblib
import pickle

In [4]:
#load dataset
from sklearn.datasets import load_iris

In [5]:
#iris has three classes of iris plants: setosa, versicolor, and virginica
data = load_iris()

In [6]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
df=pd.DataFrame(data.data, columns=data.feature_names)

In [8]:
data.target #stored as label encoded data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
df['target'] = data.target

In [10]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
df["target_names"] = df["target"].map({i:name for i,name in enumerate(data.target_names)})

In [13]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [14]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_names  
0       0       setosa  
1       0       setosa  
2       0       setosa  
3       0       setosa  
4       0       setosa

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [16]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [17]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [18]:
df["target_names"].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [19]:
#### Binary class : eliminate one class
binary_df = df[df["target"] != 2]

In [20]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [21]:
x_binary = binary_df[["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"]]

In [22]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [23]:
y_binary = binary_df[["target"]]

In [24]:
y_binary

target
0        0
1        0
2        0
3        0
4        0
..     ...
95       1
96       1
97       1
98       1
99       1

[100 rows x 1 columns]

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x_binary,y_binary,test_size = 0.2)

In [26]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.491250          3.130000           2.817500   
std             0.663171          0.482189           1.452608   
min             4.300000          2.000000           1.000000   
25%             5.000000          2.800000           1.400000   
50%             5.450000          3.100000           1.900000   
75%             5.925000          3.400000           4.400000   
max             7.000000          4.400000           5.000000   

       petal width (cm)  
count         80.000000  
mean           0.771250  
std            0.564833  
min            0.100000  
25%            0.200000  
50%            0.500000  
75%            1.300000  
max            1.800000

In [27]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [28]:
x_test = scaler.transform(x_test)

In [29]:
x_train

array([[-1.20065875,  0.14608718, -1.05126391, -1.01774165],
       [ 1.68243967, -0.48000073,  1.23484542,  0.94202345],
       [ 2.28940776,  0.14608718,  1.30412146,  1.12018392],
       [-0.74543268,  0.77217508, -0.84343579, -0.30509979],
       [-1.35240077,  0.98087105, -1.25909203, -1.01774165],
       [-0.59369066,  0.56347911, -0.91271183, -1.01774165],
       [-1.35240077, -0.06260879, -0.91271183, -1.01774165],
       [-0.74543268, -2.35826444,  0.47280897,  0.40754206],
       [ 1.53069765, -0.68869669,  1.23484542,  1.29834438],
       [ 0.16501945, -0.27130476,  1.16556938,  1.29834438],
       [ 0.31676147, -0.68869669,  1.16556938,  0.94202345],
       [ 0.31676147,  1.39826298, -0.77415975, -0.83958119],
       [ 0.92372956, -0.68869669,  0.81918918,  0.94202345],
       [-0.13846459,  1.60695895, -1.05126391, -0.66142072],
       [-1.04891673, -0.27130476, -0.98198787, -0.83958119],
       [-1.35240077,  0.56347911, -0.98198787, -0.83958119],
       [ 1.2272136 ,  0.

In [30]:
x_test

array([[-0.44194864,  0.77217508, -0.91271183, -1.01774165],
       [ 0.31676147, -0.27130476,  0.95774126,  0.76386299],
       [-0.13846459,  1.18956702, -0.91271183, -1.01774165],
       [-1.04891673,  0.56347911, -0.84343579, -1.01774165],
       [-0.74543268, -1.73217653,  0.33425689,  0.40754206],
       [ 0.62024551, -0.27130476,  0.95774126,  1.29834438],
       [-1.50414279, -1.73217653, -1.05126391, -0.83958119],
       [-0.44194864,  0.56347911, -0.98198787, -1.01774165],
       [ 0.31676147, -0.68869669,  0.88846522,  0.94202345],
       [-0.59369066,  1.39826298, -0.84343579, -1.01774165],
       [-1.20065875,  0.14608718, -0.84343579, -1.01774165],
       [-1.65588481, -0.48000073, -0.98198787, -1.01774165],
       [ 0.01327743, -1.73217653,  0.81918918,  0.94202345],
       [ 1.07547158, -0.48000073,  1.0270173 ,  0.94202345],
       [-0.13846459, -0.27130476,  1.16556938,  1.29834438],
       [ 0.16501945, -1.3147846 ,  0.74991313,  0.58570253],
       [ 1.2272136 , -1.

In [31]:
SVC_binary = SVC(kernel = 'linear',C = 1.0,probability = True)


In [32]:
SVC_binary.fit(x_train,y_train)

c:\Users\steve\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', probability=True)

In [33]:
SVC_binary.predict(x_test)

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [34]:
print(classification_report(y_test,SVC_binary.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [35]:
confusion_matrix(y_test,SVC_binary.predict(x_test))

array([[ 9,  0],
       [ 0, 11]])

In [37]:
import joblib
joblib.dump([SVC_binary,scaler],'svm_model_binary.pkl')

['svm_model_binary.pkl']

In [38]:
#experiment or play with the parameters like kernel, C, gamma, degree etc.


In [39]:
#Multiclass classification

x_multi = df[["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"]]
y_multi = df[["target"]]

In [40]:
x_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [41]:
y_multi

target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [42]:
x_train_multi, x_test_multi, y_train_multi, y_test_multi = train_test_split(x_multi, y_multi, test_size=0.2)

In [43]:
scaler = StandardScaler()
x_train_multi = scaler.fit_transform(x_train_multi)
x_test_multi = scaler.transform(x_test_multi)

In [44]:
x_train_multi

array([[-0.14053787, -1.07972807, -0.1012068 , -0.22010541],
       [ 0.10747014, -0.17524382,  0.81538306,  0.85248949],
       [ 0.97549815, -0.40136489,  0.52894873,  0.18211768],
       [-1.00856589,  0.72924043, -1.24694411, -1.29270031],
       [ 1.47151416,  0.2769983 ,  0.58623559,  0.31619204],
       [-1.13256989, -1.30584914,  0.47166186,  0.71841513],
       [ 0.35547814, -0.17524382,  0.52894873,  0.31619204],
       [-0.88456188,  0.95536149, -1.30423098, -1.29270031],
       [ 0.23147414, -1.98421232,  0.75809619,  0.4502664 ],
       [ 0.23147414, -0.17524382,  0.64352246,  0.85248949],
       [-0.14053787, -0.17524382,  0.29980126,  0.04804331],
       [ 0.85149415,  0.2769983 ,  0.81538306,  1.12063821],
       [-0.26454187, -1.30584914,  0.12794067, -0.08603105],
       [ 1.22350616, -0.62748595,  0.64352246,  0.31619204],
       [ 0.23147414,  0.72924043,  0.47166186,  0.58434076],
       [-0.14053787,  2.99045105, -1.24694411, -1.02455159],
       [ 0.85149415, -0.

In [45]:
x_test_multi

array([[-0.26454187, -0.85360701,  0.29980126,  0.18211768],
       [ 0.72749015,  0.2769983 ,  0.92995679,  1.5228613 ],
       [ 1.09950215, -1.30584914,  1.21639112,  0.85248949],
       [ 1.59551816, -0.17524382,  1.27367798,  1.25471258],
       [-1.5045819 ,  0.2769983 , -1.30423098, -1.29270031],
       [ 2.33954218, -0.17524382,  1.38825172,  1.5228613 ],
       [-0.88456188,  0.72924043, -1.24694411, -1.29270031],
       [ 1.34751016,  0.2769983 ,  1.15910425,  1.5228613 ],
       [-1.13256989,  1.18148255, -1.30423098, -1.42677468],
       [ 0.23147414, -1.98421232,  0.18522753, -0.22010541],
       [-1.38057789,  0.2769983 , -1.36151785, -1.29270031],
       [ 0.10747014,  0.2769983 ,  0.64352246,  0.85248949],
       [-0.38854587, -1.07972807,  0.414375  ,  0.04804331],
       [ 0.35547814, -1.07972807,  1.10181739,  0.31619204],
       [ 0.60348614, -1.30584914,  0.70080933,  0.4502664 ],
       [-0.14053787, -0.62748595,  0.47166186,  0.18211768],
       [ 2.33954218, -1.

In [46]:
svc_multi = SVC(kernel='linear', C=1.0, probability=True)

In [47]:
svc_multi.fit(x_train_multi, y_train_multi)

c:\Users\steve\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', probability=True)

In [48]:
svc_multi.predict(x_test_multi)

array([1, 2, 2, 2, 0, 2, 0, 2, 0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 0, 0, 1,
       2, 2, 1, 1, 1, 0, 2, 0])

In [49]:
print(classification_report(y_test_multi,svc_multi.predict(x_test_multi)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.80      0.89        10
           2       0.86      1.00      0.92        12

    accuracy                           0.93        30
   macro avg       0.95      0.93      0.94        30
weighted avg       0.94      0.93      0.93        30



In [50]:
confusion_matrix(y_test_multi,svc_multi.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0,  8,  2],
       [ 0,  0, 12]])

In [51]:
joblib.dump([svc_multi,scaler],'svm_model_multi.pkl')

['svm_model_multi.pkl']

# LOGISTIC REGRESSION

### BINARY

In [52]:
x_train, x_test, y_train, y_test = train_test_split(x_binary,y_binary,test_size = 0.2)

In [53]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
logistics_binary = LogisticRegression()
logistics_binary.fit(x_train,y_train)

c:\Users\steve\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [56]:
logistics_binary.predict(x_test)

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0])

In [57]:
print(classification_report(y_test,logistics_binary.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [58]:
confusion_matrix(y_test,logistics_binary.predict(x_test))

array([[ 9,  0],
       [ 0, 11]])

In [59]:
joblib.dump([logistics_binary,scaler],'logistic_model_binary.pkl')

['logistic_model_binary.pkl']

### Multiclass

In [60]:
x_train_multi

array([[-0.14053787, -1.07972807, -0.1012068 , -0.22010541],
       [ 0.10747014, -0.17524382,  0.81538306,  0.85248949],
       [ 0.97549815, -0.40136489,  0.52894873,  0.18211768],
       [-1.00856589,  0.72924043, -1.24694411, -1.29270031],
       [ 1.47151416,  0.2769983 ,  0.58623559,  0.31619204],
       [-1.13256989, -1.30584914,  0.47166186,  0.71841513],
       [ 0.35547814, -0.17524382,  0.52894873,  0.31619204],
       [-0.88456188,  0.95536149, -1.30423098, -1.29270031],
       [ 0.23147414, -1.98421232,  0.75809619,  0.4502664 ],
       [ 0.23147414, -0.17524382,  0.64352246,  0.85248949],
       [-0.14053787, -0.17524382,  0.29980126,  0.04804331],
       [ 0.85149415,  0.2769983 ,  0.81538306,  1.12063821],
       [-0.26454187, -1.30584914,  0.12794067, -0.08603105],
       [ 1.22350616, -0.62748595,  0.64352246,  0.31619204],
       [ 0.23147414,  0.72924043,  0.47166186,  0.58434076],
       [-0.14053787,  2.99045105, -1.24694411, -1.02455159],
       [ 0.85149415, -0.

In [61]:
x_test_multi

array([[-0.26454187, -0.85360701,  0.29980126,  0.18211768],
       [ 0.72749015,  0.2769983 ,  0.92995679,  1.5228613 ],
       [ 1.09950215, -1.30584914,  1.21639112,  0.85248949],
       [ 1.59551816, -0.17524382,  1.27367798,  1.25471258],
       [-1.5045819 ,  0.2769983 , -1.30423098, -1.29270031],
       [ 2.33954218, -0.17524382,  1.38825172,  1.5228613 ],
       [-0.88456188,  0.72924043, -1.24694411, -1.29270031],
       [ 1.34751016,  0.2769983 ,  1.15910425,  1.5228613 ],
       [-1.13256989,  1.18148255, -1.30423098, -1.42677468],
       [ 0.23147414, -1.98421232,  0.18522753, -0.22010541],
       [-1.38057789,  0.2769983 , -1.36151785, -1.29270031],
       [ 0.10747014,  0.2769983 ,  0.64352246,  0.85248949],
       [-0.38854587, -1.07972807,  0.414375  ,  0.04804331],
       [ 0.35547814, -1.07972807,  1.10181739,  0.31619204],
       [ 0.60348614, -1.30584914,  0.70080933,  0.4502664 ],
       [-0.14053787, -0.62748595,  0.47166186,  0.18211768],
       [ 2.33954218, -1.

In [62]:
y_test_multi

target
94        1
115       2
108       2
102       2
47        0
135       2
39        0
120       2
37        0
62        1
2         0
70        1
90        1
134       2
72        1
55        1
118       2
145       2
114       2
22        0
44        0
81        1
147       2
144       2
65        1
80        1
64        1
34        0
107       2
17        0

In [63]:
y_train_multi

target
79        1
149       2
58        1
7         0
50        1
..      ...
9         0
41        0
117       2
84        1
74        1

[120 rows x 1 columns]

In [64]:
logistics_ovr = LogisticRegression(multi_class='ovr',solver = "lbfgs",max_iter = 2000)

In [65]:
logistics_ovr.fit(x_train_multi,y_train_multi)

c:\Users\steve\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\steve\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='ovr')

In [66]:
print(classification_report(y_test_multi,logistics_ovr.predict(x_test_multi)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.90      0.90      0.90        10
           2       0.92      0.92      0.92        12

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



In [67]:
logistics_ovr.predict(x_test_multi)

array([1, 2, 2, 2, 0, 2, 0, 2, 0, 1, 0, 2, 1, 1, 1, 1, 2, 2, 2, 0, 0, 1,
       2, 2, 1, 1, 1, 0, 2, 0])

In [68]:
confusion_matrix(y_test_multi,logistics_ovr.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0,  9,  1],
       [ 0,  1, 11]])

In [69]:
logistics_multinomial = LogisticRegression(multi_class='multinomial',solver = "lbfgs",max_iter = 2000) # softmax
logistics_multinomial.fit(x_train_multi,y_train_multi)

c:\Users\steve\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\steve\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='multinomial')

In [70]:
logistics_multinomial.predict(x_test_multi)

array([1, 2, 2, 2, 0, 2, 0, 2, 0, 1, 0, 2, 1, 2, 1, 1, 2, 2, 2, 0, 0, 1,
       2, 2, 1, 1, 1, 0, 2, 0])

In [71]:
print(classification_report(y_test_multi,logistics_multinomial.predict(x_test_multi)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.90      0.95        10
           2       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [72]:
confusion_matrix(y_test_multi,logistics_multinomial.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0,  9,  1],
       [ 0,  0, 12]])

In [73]:
joblib.dump([logistics_ovr,scaler],'logistic_model_ovr.pkl')

['logistic_model_ovr.pkl']

In [75]:
joblib.dump([logistics_multinomial,scaler],'logistic_model_multinomial.pkl')

['logistic_model_multinomial.pkl']